# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=['/home/pi/tv.local'],
    binaries=[
        ('/usr/lib/arm-linux-gnueabihf/libpigpio.so*', '.'),
        ('/usr/lib/python3/dist-packages/pigpio.py', '.'),
        ('/usr/lib/python3/dist-packages/RPi/_GPIO.cpython-39-arm-linux-gnueabihf.so', 'RPi'),
        ('/usr/lib/python3/dist-packages/gpiozero/pins/pigpio.py', 'gpiozero/pins'),
        ('/usr/lib/arm-linux-gnueabihf/libproc2.so.0', '.'),
    ],
    datas=[
        ('static', 'static'),
        ('templates', 'templates'),
        ('lib', 'lib'),
        ('web', 'web'),
        ('images', 'images'),
        ('video', 'video'),
        ('/usr/lib/python3/dist-packages/gpiozero', 'gpiozero'),
        ('/usr/lib/python3/dist-packages/RPi', 'RPi'),
    ],
    hiddenimports=[
        'flask',
        'PIL',
        'numpy',
        'display',
        'gpiozero',
        'gpiozero.pins',
        'gpiozero.pins.lgpio',
        'gpiozero.pins.rpigpio',
        'gpiozero.pins.pigpio',
        'gpiozero.pins.native',
        'gpiozero.pins.local',
        'gpiozero.pins.mock',
        'gpiozero.pins.rpio',
        'gpiozero.pins.pi',
        'gpiozero.pins.rpi',
        'spidev',
        'RPi.GPIO',
        'RPi._GPIO',
        'lgpio',
        'pigpio',
        'numbers',
        'argparse',
        'atexit',
        'shutil',
        'subprocess',
        'socket',
        'glob',
        'threading',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'tkinter',
        'PyQt5',
        'PySide2',
        'pandas',
        'scipy',
        'sklearn',
        'tensorflow',
        'torch',
        'cv2',
        'pygame',
        'wx',
        'PyGObject',
        'gi',
        'dbus',
        '_tkinter',
        '_gtkagg',
        '_agg2',
        '_cairo',
        '_curses',
        '_decimal',
        '_hashlib',
        '_lzma',
        '_multiprocessing',
        '_opcode',
        '_posixsubprocess',
        '_ssl',
        '_testcapi',
        '_uuid',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='tvlocal',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=True,
    upx=True,
    upx_exclude=[],
    name='tvlocal',
) 